CREATE TABLE IF NOT EXISTS readers
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(128) NOT NULL,
    surname varchar(128) NOT NULL,
    phone   varchar(12)  NOT NULL UNIQUE,
    address varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS books
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            varchar(128)                   NOT NULL,
    inventory_number bigint                         NOT NULL UNIQUE,
    reader_id        bigint REFERENCES readers (id) NOT NULL
);

CREATE TABLE IF NOT EXISTS authors
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     varchar(128) NOT NULL,
    personal_info varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS author_book
(
    author_id bigint REFERENCES authors (id),
    book_id   bigint REFERENCES books (id),
    PRIMARY KEY (author_id, book_id)
);



INSERT INTO readers (name, surname, phone, address)
VALUES ('Ivan', 'Ivanov', '71111111111', 'Lenina 11'),
       ('Petr', 'Petrov', '72222222222', 'Lenina 22'),
       ('Sveta', 'Svetikova', '73333333333', 'Lenina 33');


INSERT INTO books (title, inventory_number, reader_id)
VALUES ('Title1', 11111, 1),
       ('Title2', 22222, 2),
       ('Title3', 33333, 3);

INSERT INTO authors (full_name, personal_info)
VALUES ('Author1', 'likes dogs'),
       ('Author2', 'likes cats'),
       ('Author3', 'likes wolfs');

INSERT INTO author_book (author_id, book_id)
VALUES (1, 1),
       (3, 1),
       (2, 3),
       (3, 3),
       (2, 2);

































