--liquibase formatted sql

--changeset lepd:1
CREATE TABLE IF NOT EXISTS readers
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(128) NOT NULL,
    surname varchar(128) NOT NULL,
    phone   varchar(12)  NOT NULL UNIQUE,
    address varchar(256) NOT NULL
);


--changeset lepd:2
CREATE TABLE IF NOT EXISTS books
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            varchar(128)                   NOT NULL,
    inventory_number bigint                         NOT NULL UNIQUE,
    reader_id        bigint REFERENCES readers (id) NOT NULL
);


--changeset lepd:3
CREATE TABLE IF NOT EXISTS authors
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     varchar(128) NOT NULL,
    personal_info varchar(256) NOT NULL
);


--changeset lepd:4
CREATE TABLE IF NOT EXISTS author_book
(
    author_id bigint REFERENCES authors (id),
    book_id   bigint REFERENCES books (id),
    PRIMARY KEY (author_id, book_id)
);




